# Database connection properties
db.url=jdbc:mariadb://localhost:3306/video_rental
db.user=user
db.password=1234


# Optional: JDBC driver class
db.driverClass=com.mysql.cj.jdbc.Driver

# HIkariCP properties
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
maximumPoolSize=50
